#Project deploy variables
variables:
  APP_NAME: "indeema_ci_api"
  DEPLOY_PATH: "/home/root/Indeema"
  BACKUP_PATH: "/home/root/Indeema/backups"
  JS_SERVER_FILE: "server.js"
  URL_DEV: "http://198.199.125.240:1338"
  HOST_DEV: "indeema@198.199.125.240"
#######################################################################################################
##!!!Important!!! Do not change the following code start from line 10 if you don`t know how it works!##
#######################################################################################################
stages:
  - install
  - launch
  - helthcheck
  - restore
#Jobs templates
.job_install: &tpl_install
  stage: install
  script:
    - echo "Install dependencies"
    - npm install
    - npm run build
    - echo "Compress project folder"
    - tar -czf $APP_NAME.tar.gz ./*
    - echo "Create project folder on server, where all resources will be copy to"
    - mkdir -p $DEPLOY_PATH/$APP_NAME
    - cp $APP_NAME.tar.gz /tmp
    - echo "Make backup, uncompress project, remove archive"
    - mkdir -p $BACKUP_PATH
    - rm -rf $BACKUP_PATH/$APP_NAME
    - mv $DEPLOY_PATH/$APP_NAME $BACKUP_PATH/
    - mkdir -p $DEPLOY_PATH/$APP_NAME
    - cd $DEPLOY_PATH/$APP_NAME
    - tar -xzf /tmp/$APP_NAME.tar.gz
    - rm -fr /tmp/$APP_NAME.tar.gz
    - cp -r $BACKUP_PATH/$APP_NAME/public/uploads/* $DEPLOY_PATH/$APP_NAME/public/uploads/
.job_launch: &tpl_launch
  stage: launch
  script:
    - echo "Launch back-end service"
    - source ~/.profile
    - cd $DEPLOY_PATH/$APP_NAME
    - pm2 stop $APP_NAME
    - sleep 5
    - pm2 start --name $APP_NAME npm -- start
.job_helthcheck: &tpl_helthcheck
  stage: helthcheck
  script:
    - curl $URL --connect-timeout 10 -s -f -o /dev/null && echo 'Success! API is working' || echo "Error! API is not answering on $URL"
    - curl $URL --connect-timeout 10 -s -f -o /dev/null && echo 'No need to show PM2 logs' || source ~/.profile; pm2 logs --nostream
    - curl $URL --connect-timeout 10 -s -f -o /dev/null && echo 'No need to stop deployment' || exit 1
.job_restore: &tpl_restore
  stage: restore
  script:
    - echo "Restore from previous version"
    - source ~/.profile
    - rm -fr $DEPLOY_PATH/$APP_NAME
    - mv $BACKUP_PATH/$APP_NAME $DEPLOY_PATH/$APP_NAME
    - cd $DEPLOY_PATH/$APP_NAME
    - pm2 delete $APP_NAME
    - sleep 5
    - pm2 start --name $APP_NAME npm -- start
  when: on_failure
#Stages for devevelopment
development install:
  variables:
    HOST: $DEV_HOST
  environment:
    name: development
    url: $URL_DEV
  tags:
    - web
  only:
    - ci_api_settings
  <<: *tpl_install
development launch:
  variables:
    HOST: $DEV_HOST
  environment:
    name: development
    url: $URL_DEV
  tags:
    - web
  only:
    - ci_api_settings
  <<: *tpl_launch
development helthcheck:
  variables:
    URL: $URL_DEV
    HOST: $DEV_HOST
  environment:
    name: development
    url: $URL_DEV
  tags:
    - web
  only:
    - ci_api_settings
  <<: *tpl_helthcheck
development restore:
  variables:
    HOST: $DEV_HOST
  environment:
    name: development
    url: $URL_DEV
  tags:
    - web
  only:
    - ci_api_settings
  <<: *tpl_restore
#Stages for production
production install:
  variables:
    HOST: $PROD_HOST
  environment:
    name: production
    url: $URL_PROD
  tags:
    - scripts
  only:
    - ci_api
  <<: *tpl_install
production launch:
  variables:
    HOST: $PROD_HOST
  environment:
    name: production
    url: $URL_PROD
  tags:
    - scripts
  only:
    - ci_api
  <<: *tpl_launch
production helthcheck:
  variables:
    URL: $URL_PROD
    HOST: $PROD_HOST
  environment:
    name: production
    url: $URL_PROD
  tags:
    - scripts
  only:
    - ci_api
  <<: *tpl_helthcheck
production restore:
  variables:
    HOST: $PROD_HOST
  environment:
    name: production
    url: $URL_PROD
  tags:
    - scripts
  only:
    - ci_api
  <<: *tpl_restore
